services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    env_file:
      - "./frontend/.env.production"
    ports:
      - "3000:80"
    networks:
      - pong_network
    restart: always
  
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    env_file:
      - "./backend/.env"
    volumes:
      - backend_vol:/app
    networks:
      - pong_network
    restart: always

volumes:
  back_end_vol:
    name: back_end_vol
    driver: local
    driver_opts:
      type: none
      device: srcs
      o: bind

networks:
  pong_network:
    dirver: bridge

